@startuml
title 修改密码顺序图
actor user
user -> 修改密码窗口: 填写原始密码、新密码和确认密码
修改密码窗口 -> 修改密码窗口: 检查新密码和确认密码是否一致
修改密码窗口 -> USERS: 核对原始密码是否正确
alt 原始密码正确
    USERS->修改密码窗口: 返回修改密码成功
    修改密码窗口-> user: 提示用户修改密码成功
else 用户名或密码错误
    USERS->修改密码窗口: 返回原始密码密码错误
    修改密码窗口-> user: 提示用户原始密码不正确
else 
end
@enduml