@startuml 借阅书籍
actor 借阅者

activate 借阅者
activate 用户登录窗口
activate 借阅书籍窗口
database 数据库
借阅者 -> 用户登录窗口: 输入账号密码登录系统
用户登录窗口 -> 数据库: 账号密码匹配
activate 数据库
数据库 --> 用户登录窗口: 返回登录结果
用户登录窗口 --> 借阅者: 登录成功

借阅者 -> 借阅书籍窗口: 输入借阅书籍信息
借阅书籍窗口 -> 数据库: 根据信息检索书籍
数据库 --> 借阅书籍窗口: 返回检索结果
借阅书籍窗口 --> 借阅者: 显示检索结果

借阅者 --> 借阅书籍窗口: 确认借阅书籍
借阅书籍窗口 --> 数据库: 记录借阅信息
数据库 --> 借阅书籍窗口: 返回借阅结果
借阅书籍窗口 --> 借阅者: 显示借阅结果
@enduml