@startuml 预订书籍
actor 借阅者

activate 借阅者
activate 预订书籍窗口
database 数据库

借阅者 -> 预订书籍窗口: 输入预订书籍信息
预订书籍窗口 -> 数据库: 根据信息检索书籍

activate 数据库
数据库 --> 预订书籍窗口: 返回检索结果
预订书籍窗口 --> 借阅者: 显示检索结果
借阅者 --> 预订书籍窗口: 确认预订书籍
预订书籍窗口 --> 数据库: 记录预订信息
数据库 --> 预订书籍窗口: 返回预订结果
预订书籍窗口 --> 借阅者: 显示借阅结果
@enduml