@startuml 归还书籍
actor 借阅者
actor 图书管理员

activate 借阅者
activate 图书管理员
activate 归还书籍窗口
database 数据库

借阅者 --> 图书管理员: 归还书籍
图书管理员 --> 图书管理员: 检查书籍是否损坏
图书管理员 --> 归还书籍窗口: 输入借阅者id

activate 数据库
数据库 --> 归还书籍窗口: 返回该用户借书记录
归还书籍窗口 --> 图书管理员: 显示借阅记录
图书管理员 --> 归还书籍窗口: 选择归还书籍
归还书籍窗口 --> 数据库: 消除借阅记录
数据库 --> 归还书籍窗口: 返回归还结果
归还书籍窗口 --> 图书管理员: 显示归还结果
图书管理员 --> 借阅者: 归还成功
@enduml